### ISSUE TITLE
Support version 1.17.0+

### ISSUE THREAD

**Issue by noahjohnhay** [FeryET/asdf-container-structure-test#6]
**Is your feature request related to a problem? Please describe.**

In version 1.17.0 they have changed where the artifacts are stored see https://github.com/GoogleContainerTools/container-structure-test/releases/tag/v1.17.0 

> Releases are no longer published to GCS, use the github release asset to access the binary.

**Describe the solution you'd like**

Update to use github artifact store 

**Describe alternatives you've considered**

I don't think there are many alternative options other than convincing the tool owner to continue to publish to GCS which seems unlikely.

**Additional context**

**Comment by FeryET** [comment]
@noahjohnhay Thank you for point the issue out.

This is now fixed in the latest version of this plugin.
